apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  selector:
    matchLabels:
      run: python-flask-app
  replicas: 2
  template:
    metadata:
      labels:
        run: python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: nishanthkp/python-flask-app:15
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: python-flask-app
  labels:
    run: python-flask-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    run: python-flask-app